apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tarmac-portal
  description: Tarmac internal developer portal (Backstage)
  annotations:
    github.com/project-slug: tarmac-platform/tarmac
spec:
  type: website
  owner: guests
  lifecycle: experimental
